alpha/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('auth_part.urls')),
    url(r'^plant/', include('plants.urls')),
    url(r'^sensor/', include('sensors.urls')),

]

auth_part/urls.py
from django.conf.urls import url
from . import views

app_name='auth_part'

urlpatterns = [
    url(r'^newuser/$', views.create_profile, name='createprofile'),
    url(r'^addwaterdata/$', views.addwaterdata, name='addwaterdata' ),
    # url(r'^editwaterdata/$', views.editwaterdata, name='editwaterdata' ),
    url(r'^search_waterdata/$', views.search_waterdata, name='search_waterdata' ),
    url(r'^search_result/$', views.search_result, name='search_result' ),
    url(r'^all_waterdata/$', views.all_waterdata, name='all_waterdata'),
    url(r'^all_waterdata/update/(?P<result_id>[0-9A-Za-z\.@\-\ ]+)/$', views.update_result, name='update'),
    url(r'^all_waterdata/delete/(?P<result_id>[0-9A-Za-z\.@\-\ ]+)/$', views.delete_result, name='delete'),
    url(r'^$', views.login, name='login'),
    url(r'^logout/', views.logout_view, name='logout'), #directly logging out by importing logout in view and using it here.   
]

auth_part/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
# Create your models here.

'''class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    CHOICES = (
        ('U', 'USER'),
        ('P', 'PLANT'),
    )
    position = models.CharField(
        max_length=2,
        choices=CHOICES,
        default='U',
    )

    def __repr__(self):
        return self.user.username

    def __str__(self):
        return self.user.username
        
'''
class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

'''class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['position']  
'''          

        

auth_part/forms.py
from django import forms
from  plants.models import Waterdata
#DataFlair
class WaterdataCreate(forms.ModelForm):
	class Meta:
	    model = Waterdata
	    fields = '__all__'

auth_part/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import  UserForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, logout, login as auth_login
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from plants.models import Waterdata

from .forms import WaterdataCreate
from django.http import HttpResponse

from django.db.models import Q
from django.shortcuts import render, redirect

# Create your views here.

#@csrf_exempt
def login(request):
    print(request.POST, request.GET)
    print(12345)
    form = UserForm()
    #if request.user != None:
    #    return HttpResponseRedirect(reverse('plants:dashboard'))
    if request.POST.get('username') and request.POST.get('password') and request.method == 'POST':
        user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
        if user:
            print(user)
            auth_login(request, user)
            return HttpResponseRedirect(reverse('plants:dashboard'))
            #return render(request, 'userdashboard.html', context={'username': user.username})
    return render(request, 'index.html', context={'form': form})

def logout_view(request):
    print(741852963)
    logout(request)
    #print (request.user, "request.user")
    return HttpResponseRedirect(reverse('auth_part:login'))

#@csrf_exempt
def create_profile(request):
    error = ""
    if request.method == 'POST':
        print('yoyo')
        userform = UserForm(request.POST)
        #profileform = ProfileForm(request.POST)
        if userform.is_valid() and (len(User.objects.filter(email=request.POST.get('email')))==0):
            print('yoyo2')
            user = User.objects.create_user(**userform.cleaned_data)
            auth_login(request, user)
            return HttpResponseRedirect(reverse('plants:dashboard'))
            #return HttpResponse(status=200)
        else:
            error = "Username or email already in use."
            print(error)

            return render(request, 'register.html', context={'sign_up': True, 'error': error, 'tried': True})
            
    
    userform = UserForm()
    return render(request, 'register.html', context={'sign_up': True, 'error': error})
           
    

def addwaterdata(request):
    error = ""
    if request.method == 'POST':
        print('yoyo')
        district=request.POST.get('district', False)
        zone=request.POST.get('zone', False)
        settlement=request.POST.get('settlement', False)
        block=request.POST.get('block', False)
        cluster=request.POST.get('cluster', False)
        source=request.POST.get('source', False)
        dwdnum=request.POST.get('dwdnum', False)
        ycord=request.POST.get('ycord', False)
        xcord=request.POST.get('xcord', False)
        parameter=request.POST.get('parameter', False)
        freeresid=request.POST.get('freeresid', False)
        turbidity=request.POST.get('turbidity', False)
        ecol=request.POST.get('ecol', False)
        ph=request.POST.get('ph', False)

        print ("PH Data %s" % (ph))
      
        adddata = Waterdata(user=request.user, district=district,zone=zone,settlement=settlement,block=block,cluster=cluster,source=source,dwdnum=dwdnum,ycord=ycord,xcord=xcord,parameter=parameter,freeresid=freeresid,turbidity=turbidity,ecol=ecol,ph=ph)
        adddata.save()

        return render(request, 'addwaterdata.html', context={'sign_up': True, 'error': error, 'tried': True})
            
   
    return render(request, 'addwaterdata.html', context={'sign_up': True, 'error': error})
           





def search_result(request):
    query = request.GET.get('q')
    results =Waterdata.objects.filter(Q(district__icontains=query) | Q(zone__icontains=query) | Q(settlement__icontains=query) | Q(block__icontains=query) | Q(cluster__icontains=query) | Q(borehole__icontains=query))

    return render(request, 'view_waterdata.html', {'results': results})

def search_waterdata(request):
 
    return render(request, 'search_waterdata.html', {})



def all_waterdata(request):
 
    results =Waterdata.objects.all()
    return render(request, 'all_waterdata.html', {'results':results})


def update_result(request, result_id):
    result_id = int(result_id)
    results = None
    try:
        waterdata_sel = Waterdata.objects.get(id = result_id)
    except Waterdata.DoesNotExist:
        return redirect('/all_waterdata/')
    waterdata_form = WaterdataCreate(request.POST or None, instance = waterdata_sel)
    if waterdata_form.is_valid():
       waterdata_form.save()
       results =Waterdata.objects.all()
       return redirect('/all_waterdata/')
       
    return render(request, 'editwaterdata.html', {'waterdata_form':waterdata_form, 'result_id':result_id})





def delete_result(request, result_id):
    waterdata_id = int(result_id)
    try:
        waterdata_sel = Waterdata.objects.get(id = waterdata_id)
    except Waterdata.DoesNotExist:
        return redirect('/all_waterdata/')
    waterdata_sel.delete()
    return redirect('/all_waterdata/')

auth_part/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Login</title>
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'auth_part/css/sb-admin.css' %}" rel="stylesheet">
</head>

<body class="bg-dark">
  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header text-center">Login to your Water system account</div>
      <div class="card-body">
        <form action="/" method="post">
            {% csrf_token %}  
          <div class="form-group">
            <label for="exampleInputEmail1">Username</label>
            <input class="form-control" name="username" id="exampleInputName" type="name" aria-describedby="nameHelp" placeholder="Enter Username">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input class="form-control" name="password" id="exampleInputPassword1" type="password" placeholder="Password">
          </div>
          <!--<div class="form-group">
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" type="checkbox"> Remember Password</label>
            </div>
          </div>-->
          <button value="submit" type="submit" class="btn btn-primary btn-block" href="{% url 'auth_part:login'%}">Login
          </button>
        </form>
        <div class="text-center">
          <a class="d-block small mt-3" href="{% url 'auth_part:createprofile'%}">Register an Account</a>
        </div>
      </div>
    </div>
  </div>
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'auth_part/js/jquery.min.js' %}"></script>
  <script src="{% static 'auth_part/js/bootstrap.bundle.min.js' %}"></script>
  <!-- Core plugin JavaScript-->
  <script src="{% static 'auth_part/js/jquery.easing.min.js' %}"></script>
</body>

</html>

auth_part/templates/index1.html
{% load staticfiles %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Login | Register  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
  
  <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans'>

      <link rel="stylesheet" href="{% static 'auth_part/css/style.css' %}">

  
</head>

<body>
  <div class="cont">
  <div class="demo">
    {% if sign_up %}      
      <form class="demo" action="/newuser/" method="post">
    {% else %}
      <form  class="demo" action="/" method="post">
    {% endif %}
    {% csrf_token %}        
      <div class="login">
        <div class="login__check"></div>
        <div class="login__form">
          {%if tried%}
          <p style="font-size: 1rem;">{{error}}</p>  
          {%endif%}          
          {% if sign_up %}
          <div class="login__row">
              <img style="height:25px; width:30px; float:left; margin-top:8px;" src="{% static 'auth_part/images/mail1.svg' %}" />
              <input type="text" name="email" class="login__input name" placeholder="Email ID"/>                                      
          </div>
          {% endif %}
          <div class="login__row">
            <svg class="login__icon name svg-icon" viewBox="0 0 20 20">
              <path d="M0,20 a10,8 0 0,1 20,0z M10,0 a4,4 0 0,1 0,8 a4,4 0 0,1 0,-8" />
            </svg>
            <input type="text" name="username" class="login__input name" placeholder="Username"/>
          </div>
          <div class="login__row">
            <svg class="login__icon pass svg-icon" viewBox="0 0 20 20">
              <path d="M0,20 20,20 20,8 0,8z M10,13 10,16z M4,8 a6,8 0 0,1 12,0" />
            </svg>
            <input type="password" name="password" class="login__input pass" placeholder="Password"/>
          </div>
          {% if sign_up %}
          <button type="submit" class="login__submit">Sign Up</button>
          <center><p class="login__signup"><a href="{% url 'auth_part:login'%}">Login</a></p></center>
          
          {% else %}
          <button type="submit"  class="login__submit">Sign in</button>
          <p class="login__signup">Don't have an account? &nbsp;<a href="{% url 'auth_part:createprofile'%}">Sign up</a></p>
          {% endif %}
        </div>
      </form>        
      </div>
      <div class="app">
        <div class="app__top">
          <div class="app__menu-btn">
            <span></span>
          </div>
          <svg class="app__icon search svg-icon" viewBox="0 0 20 20">
            <!-- yeap, its purely hardcoded numbers straight from the head :D (same for svg above) -->
            <path d="M20,20 15.36,15.36 a9,9 0 0,1 -12.72,-12.72 a 9,9 0 0,1 12.72,12.72" />
          </svg>
          <p class="app__hello">Good Morning!</p>
          <div class="app__user">
            <img src="//s3-us-west-2.amazonaws.com/s.cdpn.io/142996/profile/profile-512_5.jpg" alt="" class="app__user-photo" />
            <span class="app__user-notif">3</span>
          </div>
          <div class="app__month">
            <span class="app__month-btn left"></span>
            <p class="app__month-name">March</p>
            <span class="app__month-btn right"></span>
          </div>
        </div>
        <div class="app__bot">
          <div class="app__days">
            <div class="app__day weekday">Sun</div>
            <div class="app__day weekday">Mon</div>
            <div class="app__day weekday">Tue</div>
            <div class="app__day weekday">Wed</div>
            <div class="app__day weekday">Thu</div>
            <div class="app__day weekday">Fri</div>
            <div class="app__day weekday">Sad</div>
            <div class="app__day date">8</div>
            <div class="app__day date">9</div>
            <div class="app__day date">10</div>
            <div class="app__day date">11</div>
            <div class="app__day date">12</div>
            <div class="app__day date">13</div>
            <div class="app__day date">14</div>
          </div>
          <div class="app__meetings">
            <div class="app__meeting">
              <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/142996/profile/profile-80_5.jpg" alt="" class="app__meeting-photo" />
              <p class="app__meeting-name">Feed the cat</p>
              <p class="app__meeting-info">
                <span class="app__meeting-time">8 - 10am</span>
                <span class="app__meeting-place">Real-life</span>
              </p>
            </div>
            <div class="app__meeting">
              <img src="//s3-us-west-2.amazonaws.com/s.cdpn.io/142996/profile/profile-512_5.jpg" alt="" class="app__meeting-photo" />
              <p class="app__meeting-name">Feed the cat!</p>
              <p class="app__meeting-info">
                <span class="app__meeting-time">1 - 3pm</span>
                <span class="app__meeting-place">Real-life</span>
              </p>
            </div>
            <div class="app__meeting">
              <img src="//s3-us-west-2.amazonaws.com/s.cdpn.io/142996/profile/profile-512_5.jpg" alt="" class="app__meeting-photo" />
              <p class="app__meeting-name">FEED THIS CAT ALREADY!!!</p>
              <p class="app__meeting-info">
                <span class="app__meeting-time">This button is just for demo ></span>
              </p>
            </div>
          </div>
        </div>
        <div class="app__logout">
          <svg class="app__logout-icon svg-icon" viewBox="0 0 20 20">
            <path d="M6,3 a8,8 0 1,0 8,0 M10,0 10,12"/>
          </svg>
        </div>
      </div>
    </div>
</div>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script  src="{% static 'auth_part/js/index.js' %}"></script>

</body>
</html>

auth_part/templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Register</title>
  <!-- Bootstrap core CSS-->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  <!-- Custom styles for this template-->
  <link href="{% static 'auth_part/css/sb-admin.css' %}" rel="stylesheet">
</head>

<body class="bg-dark">
  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header text-center">Register an Account for your Water system </div>
      <div class="card-body">
        <form action="/newuser/" method="post">
        {% csrf_token %} 
          <div class="form-group">
            <div class="form-row">
              <div class="col-md-12">
                <label for="exampleInputName">Name</label>
                <input class="form-control" name="username" id="exampleInputName" type="text" aria-describedby="nameHelp" placeholder="Enter first name">
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="form-row">
              <div class="col-md-12">
                <label for="exampleInputEmail1">Email address</label>
                <input class="form-control" name="email" id="exampleInputEmail1" type="text" aria-describedby="emailHelp" placeholder="Enter email">
              </div>
            </div>
          </div>  
          <div class="form-group">
            <div class="form-row">
              <div class="col-md-12">
                <label for="exampleInputPassword1">Password</label>
                <input class="form-control" name="password" id="exampleInputPassword1" type="password" placeholder="Password">
              </div>
            </div>
          </div>
          <button value="submit" class="btn btn-primary btn-block col-md-12" href="{% url 'auth_part:login'%}">Register</button>
        </form>
        <div class="text-center">
          <a class="d-block small mt-3 col-md-12" href="/">Login Page</a>
        </div>
      </div>
    </div>
  </div>
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'auth_part/js/jquery.min.js' %}"></script>
  <script src="{% static 'auth_part/js/bootstrap.bundle.min.js' %}"></script>
  <!-- Core plugin JavaScript-->
  <script src="{% static 'auth_part/js/jquery.easing.min.js' %}"></script>

</body>

</html>