alpha/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('auth_part.urls')),
    url(r'^plant/', include('plants.urls')),
    url(r'^sensor/', include('sensors.urls')),

]

auth_part/urls.py
from django.conf.urls import url
from . import views

app_name='auth_part'

urlpatterns = [
    url(r'^newuser/$', views.create_profile, name='createprofile'),
    url(r'^addwaterdata/$', views.addwaterdata, name='addwaterdata' ),
    # url(r'^editwaterdata/$', views.editwaterdata, name='editwaterdata' ),
    url(r'^search_waterdata/$', views.search_waterdata, name='search_waterdata' ),
    url(r'^search_result/$', views.search_result, name='search_result' ),
    url(r'^all_waterdata/$', views.all_waterdata, name='all_waterdata'),
    url(r'^all_waterdata/update/(?P<result_id>[0-9A-Za-z\.@\-\ ]+)/$', views.update_result, name='update'),
    url(r'^all_waterdata/delete/(?P<result_id>[0-9A-Za-z\.@\-\ ]+)/$', views.delete_result, name='delete'),
    url(r'^$', views.login, name='login'),
    url(r'^logout/', views.logout_view, name='logout'), #directly logging out by importing logout in view and using it here.   
]

plants/urls.py
from django.conf.urls import url
from .views import add_plant, viewdashboard, plantboard, last_readings
app_name='plants'
urlpatterns=[
    url(r'^add/$', add_plant, name='addplant' ),
    url(r'^dashboard/$', viewdashboard, name='dashboard' ),
    
    url(r'^(?P<username>[0-9A-Za-z\.@\-\ ]+)/tables', last_readings, name='last-readings'),    

    url(r'^(?P<username>[0-9A-Za-z\.@\-\ ]+)/$', plantboard, name='plantboard'),

    
]

plants/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.
class Plant(models.Model):
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    parent = models.ForeignKey(User, on_delete=models.CASCADE)
    alias  = models.CharField(max_length=20, default=None, null=True, blank=True)
    lat = models.FloatField(default = 13.5115)
    lon = models.FloatField(default = 80.0144)

    def __str__(self):
        if self.alias:
            return self.alias
        return str(self.id)

    def get_absolute_url(self):
        return "/plant" +  "/"+ str(self.alias)



class Waterdata(models.Model):
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    district  = models.CharField(max_length=20, default=None, null=True, blank=True)
    zone  = models.CharField(max_length=200, default=None, null=True, blank=True)
    settlement  = models.CharField(max_length=200, default=None, null=True, blank=True)
    block  = models.CharField(max_length=20, default=None, null=True, blank=True)
    cluster  = models.CharField(max_length=20, default=None, null=True, blank=True)
    source  = models.CharField(max_length=200, default=None, null=True, blank=True)
    dwdnum = models.CharField(max_length=200, default=None, null=True, blank=True)
    ycord  = models.CharField(max_length=200, default=None, null=True, blank=True)
    xcord  = models.CharField(max_length=200, default=None, null=True, blank=True)
    parameter  = models.CharField(max_length=200, default=None, null=True, blank=True)
    freeresid = models.CharField(max_length=100, default=None, null=True, blank=True)
    turbidity  = models.CharField(max_length=80, default=None, null=True, blank=True)
    ecol  = models.CharField(max_length=20, default=None, null=True, blank=True)
    ph  = models.CharField(max_length=20, default=None, null=True, blank=True)


    def get_absolute_url(self):
        return "/plant" +  "/"+ str(self.id)

plants/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse
from django.forms.models import model_to_dict
from sensors.models import Sensor, SensorData, Actuator


from .models import Plant,Waterdata

# Create your views here.
@login_required(login_url='/')
@csrf_exempt
def add_plant(request):
    if request.method == 'POST':
        plant = Plant()
        if (not request.POST.get('alias')) or len(Plant.objects.filter(alias=request.POST.get('alias')))!=0 :
            return HttpResponseRedirect(reverse('plants:dashboard'))
        plant.alias = request.POST.get('alias')
        plant.parent = request.user
        plant.save()
        sensor1 = Sensor()
        sensor1.sensor_type = 'Temperature'
        sensor1.parent = plant
        sensor1.save()
        sensor2 = Sensor()
        sensor2.sensor_type = 'Humidity'
        sensor2.parent = plant
        sensor2.save()
        sensor3 = Sensor()
        sensor3.sensor_type = 'Soil Moisture'
        sensor3.parent = plant
        sensor3.save()
        sensor4 = Sensor()
        sensor4.sensor_type = 'Water Level'
        sensor4.parent = plant
        sensor4.save()
        sensor5 = Sensor()
        sensor5.parent = plant
        sensor5.sensor_type = 'RainSensor'
        sensor5.save()
        actuator = Actuator()
        actuator.parent = plant
        actuator.name = request.POST.get('alias')
        actuator.state = 0
        actuator.save()

        return HttpResponseRedirect(reverse('plants:dashboard'))
    return HttpResponseRedirect(reverse('plants:dashboard'))

@login_required(login_url='/')
def viewdashboard(request):
    print(request.user)
    plants = Plant.objects.filter(parent=request.user)
    print(plants)
    return render(request, 'userdashboard.html', {'username': request.user.username, 'plants': plants})


@login_required(login_url='/')
def last_readings(request, username):
    print (username)
    plant = Plant.objects.get(alias=username, parent=request.user)
    print(plant.alias)
    sensors = plant.sensor_set.all()
    rain_values = SensorData.objects.filter(parent__sensor_type='RainSensor', parent__parent=plant)[0:100]
    rain_values = list(map(lambda x: model_to_dict(x), rain_values))
    temp_values = SensorData.objects.filter(parent__sensor_type='Temperature', parent__parent=plant)[:100]
    temp_values = list(map(lambda x: model_to_dict(x), temp_values))
    moisture_values = SensorData.objects.filter(parent__sensor_type='Soil Moisture', parent__parent=plant)[:100]
    moisture_values = list(map(lambda x: model_to_dict(x), moisture_values))

    wl_values = SensorData.objects.filter(parent__sensor_type='Water Level', parent__parent=plant)[:100]
    wl_values = list(map(lambda x: model_to_dict(x), wl_values))

    humidity_values = SensorData.objects.filter(parent__sensor_type='Humidity', parent__parent=plant)[:100]
    humidity_values = list(map(lambda x: model_to_dict(x), humidity_values))
    dict1={'temp_values':temp_values,'rain_values':rain_values,'moisture_values':moisture_values,'wl_values':wl_values,'humidity_values':humidity_values}
    return JsonResponse(dict1, safe=False)

@login_required(login_url='/')
def plantboard(request, username):
    print (username)
    plant = Plant.objects.get(alias=username, parent=request.user)
    print(plant.alias)
    sensors = plant.sensor_set.all()
    print(sensors)
    rain_sensor = sensors.filter(sensor_type='RainSensor')[0]
    temp_sensor = sensors.filter(sensor_type='Temperature')[0]
    hum_sensor = sensors.filter(sensor_type='Humidity')[0]
    moisture_sensor = sensors.filter(sensor_type='Soil Moisture')[0]
    wl_sensor = sensors.filter(sensor_type='Water Level')[0]
    sensor_data_temp = SensorData.objects.filter(parent=temp_sensor)
    sensor_data_hum = SensorData.objects.filter(parent=hum_sensor)
    sensor_data_wlevel = SensorData.objects.filter(parent=wl_sensor)
    sensor_data_mois = SensorData.objects.filter(parent=moisture_sensor)
    sensor_data_rain = SensorData.objects.filter(parent=rain_sensor)
    act = Actuator.objects.get(parent__alias=username, name=plant.alias)
    try:
        temp = sensor_data_temp.latest('id')
    except Exception:
        temp = None
    try:
        hum = sensor_data_hum.latest('id')
    except Exception:
        hum = None
    try:
        wlevel = sensor_data_wlevel.latest('id')
    except Exception:
        wlevel = None
    try:
        mois = sensor_data_mois.latest('id')
    except Exception:
        mois = None
    try:
        rain = sensor_data_rain.latest('id')
    except Exception:
        rain = None
    temp_values = list(map(lambda x: x.value, list(sensor_data_temp)[-1:-11:-1]))
    soil_values = list(map(lambda x: x.value, list(sensor_data_mois)[-1:-11:-1]))
    hum_values = list(map(lambda x: x.value, list(sensor_data_hum)[-1:-11:-1]))
    #ldr_values = list(map(lambda x: x.value, list(sensor_data_hum)[-1:-11:-1]))
    rain_values = list(map(lambda x: x.value, list(sensor_data_rain)[-1:-11:-1]))

    context={'plant': plant,
     'sensors':sensors,
     'temp': temp,
     'humidity': hum,
     'moisture': mois,
     'wlevel': wlevel,
     'rain':rain,
     'act': act,
     'temp_values':temp_values[::-1],
     'soil_values':soil_values[::-1],
     'humidity_values': hum_values[::-1],
     'rain_values': rain_values[::-1]
     }
    print(context)
    return render(request, "plant1.html", context=context)
    return HttpResponse(str(id))

plants/templates/all_waterdata.html
{% load staticfiles%}
<!DOCTYPE HTML>

<html>
	<head>
		<title>Water Management System</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'plants/css/main.css' %}" />
		<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">-->

		<!-- Data display in table with bootstrap -->
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

		
	</head>
	<body>

		<!-- Header -->			<div id="header">

				<div class="top">

					<!-- Logo -->
						<div id="logo">
							<span class="image avatar48" style="background-color:inherit !important;"><img src="{% static 'plants/images/man.svg' %}" alt="" /></span>
							<h1 id="title">{{ username }}</h1>
							
						</div>

					<!-- Nav -->
						<nav id="nav">
							<!--

								Prologue's nav expects links in one of two formats:

								1. Hash link (scrolls to a different section within the page)

								   <li><a href="#foobar" id="foobar-link" class="icon fa-whatever-icon-you-want skel-layers-ignoreHref"><span class="label">Foobar</span></a></li>

								2. Standard link (sends the user to another page/site)

								   <li><a href="http://foobar.tld" id="foobar-link" class="icon fa-whatever-icon-you-want"><span class="label">Foobar</span></a></li>

							-->
							<ul>
								<!-- <li><a href="#top" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-home">Map</span></a></li> -->
								<li><a href="#about" id="about-link" class="skel-layers-ignoreHref"><span class="icon fa-user">About Us</span></a></li>
								<li><a href="/addwaterdata/" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">Add Water Data</span></a></li>
								<li><a href="/search_waterdata/" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">Search Water Data</span></a></li>
								<li><a href="/all_waterdata/" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">All Water Data</span></a></li>
								<a href="{% url 'auth_part:logout' %}"><button style="margin-right: 20px;margin-top: 10px;">Logout</button></a>								
								<center><li>Your  Water Data</li></center>
								<hr/>								
								{% for plant in plants %}
									{% if plant.alias %}
										<a style="text-align:center;" href="{{plant.get_absolute_url}}"><div style="font-size:1rem; font-weight:bold;">{{plant.alias}}</div></a><hr/>
									{% else %}
										<a style="text-align:center;" href="{{plant.get_absolute_url}}"><div style="font-size:1rem; font-weight:bold;">{{plant.alias}}</div></a><hr/>
									{% endif %}		
									</a>
								{% endfor %}
							</ul>
						</nav>

				</div>

			<!--	<div class="bottom">

					
						<ul class="icons">
							<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon fa-faceresult"><span class="label">Faceresult</span></a></li>
							<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
							<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
							<li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
						</ul>

				</div> -->

			</div>

		<!-- Main -->
			<div id="main">

				<!-- Intro -->
				
						<div class="container">

					
							  <div class="card-header text-center">Water Quality data </div>
					      
					        
								<table class="table table-bordered">
								 <thead>
								 <tr>
								 <th>User</th>
								 <th>District </th>
								 <th>Zone</th>
								 <th>Settlement </th>

								 <th>Block </th>
								 <th>Cluster </th>
								 <th>Source </th>
								 <th>Dwd Number</th>
								 <th>Y Coordinates </th>
								 <th>X Coordinates</th>
								 <th>Parameter</th>
								 <th>Free Resident</th>
								 <th>Turbidity </th>
								 <th>Ecol  </th>
								 <th>PH Number</th>
								 </tr>



								 </thead>
								 <tbody>
								 	{% for result in results %}
								 <tr>

								 <td> {{result.user}}</td>
								 <td> {{result.district}}</td>
								 <td>{{result.zone}} </td>
								 <td> {{result.settlement}}</td>

								 <td> {{result.block}}</td>
								 <td> {{result.cluster}}</td>
								 <td>{{result.source}} </td>
								 <td> {{result.dwdnum}}</td>

								 <td> {{result.ycord}}</td>
								 <td> {{result.xcord}}</td>
								 <td>{{result.parameter}} </td>
								 <td> {{result.freeresid}}</td>
								 <td> {{result.turbidity}}</td>
								  <td> {{result.ecol}}</td>
								   <td> {{result.ph}}</td>

						           {% if request.user.is_superuser %}
								   <td><a href="update/{{result.id}}" class="btn btn-warning" id = '{{result.id}}'>edit</a></td>
							       <td><a href="delete/{{result.id}}" class="btn btn-danger" id = '{{result.id}}'>delete</a></td>
									{% endif %}
								 </tr>

							{% endfor %}


								</table>
					  
						</div>
				

			

				<!-- About Us -->
					<section id="about" class="three">
						<div class="container">

							<header>
								<h2>About Us</h2>
							</header>


						</div>
					</section>

				<!-- Contact -->
					<section id="contact" class="four">
						
							

					</section>

			</div>

		<!-- Footer -->
			<div id="footer">
				<hr style="clear:both;margin-bottom:3%; width:80%;border: 1.5px solid #988;">
				<!-- Copyright -->
					<ul class="copyright" style="float:right;margin-right:100px;">
						<li>Designed by: <a href="#" target="blank">Group 12</a></li>
					</ul>

			</div>

		<!-- Scripts -->
			<script src="{% static 'plants/js/jquery.min.js' %}"></script>
			<script src="{% static 'plants/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'plants/js/jquery.scrollzer.min.js' %}"></script>
			<script src="{% static 'plants/js/skel.min.js' %}"></script>
			<script src="{% static 'plants/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'plants/js/main.js' %}"></script>

	</body>
</html>

plants/templates/search_waterdata.html
{% load staticfiles%}
<!DOCTYPE HTML>

<html>
	<head>
		<title>Water Management System</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'plants/css/main.css' %}" />
		<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">-->
		
	</head>
	<body>

		<!-- Header -->			<div id="header">

				<div class="top">

					<!-- Logo -->
						<div id="logo">
							<span class="image avatar48" style="background-color:inherit !important;"><img src="{% static 'plants/images/man.svg' %}" alt="" /></span>
							<h1 id="title">{{ username }}</h1>
							
						</div>

					<!-- Nav -->
						<nav id="nav">
							<!--

								Prologue's nav expects links in one of two formats:

								1. Hash link (scrolls to a different section within the page)

								   <li><a href="#foobar" id="foobar-link" class="icon fa-whatever-icon-you-want skel-layers-ignoreHref"><span class="label">Foobar</span></a></li>

								2. Standard link (sends the user to another page/site)

								   <li><a href="http://foobar.tld" id="foobar-link" class="icon fa-whatever-icon-you-want"><span class="label">Foobar</span></a></li>

							-->
							<ul>
								<!-- <li><a href="#top" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-home">Map</span></a></li> -->
								<li><a href="#about" id="about-link" class="skel-layers-ignoreHref"><span class="icon fa-user">About Us</span></a></li>
								<li><a href="/addwaterdata/" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">Add Water Data</span></a></li>
								<li><a href="/search_waterdata/" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">Search Water Data</span></a></li>
								<li><a href="/all_waterdata/" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">All Water Data</span></a></li>
								<a href="{% url 'auth_part:logout' %}"><button style="margin-right: 20px;margin-top: 10px;">Logout</button></a>								
								<center><li>Your  Water Data</li></center>
								<hr/>								
								{% for plant in plants %}
									{% if plant.alias %}
										<a style="text-align:center;" href="{{plant.get_absolute_url}}"><div style="font-size:1rem; font-weight:bold;">{{plant.alias}}</div></a><hr/>
									{% else %}
										<a style="text-align:center;" href="{{plant.get_absolute_url}}"><div style="font-size:1rem; font-weight:bold;">{{plant.alias}}</div></a><hr/>
									{% endif %}		
									</a>
								{% endfor %}
							</ul>
						</nav>

				</div>

			<!--	<div class="bottom">

					
						<ul class="icons">
							<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
							<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
							<li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
						</ul>

				</div> -->

			</div>

		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">

					
							  <div class="card-header text-center">Search By</div>
					      <div class="card-body">
					        <form action="/search_result/" method="get">
					        {% csrf_token %} 
					         
					          <div class="form-group">
					            <div class="form-row">
					              <div class="col-md-12">
					                <label for="exampleInputName">Search</label>
					                <input class="form-control" name="q" id="exampleInputName" type="text" aria-describedby="nameHelp" placeholder="Enter data">
					              </div>
					            </div>
					          </div>


					          </div>
					          <button value="submit" class="btn btn-primary btn-block col-md-12">Submit Data</button>
					        </form>
					        
					      </div>
					    </div>
						</div>
					</section>

			

				<!-- About Us -->
					<section id="about" class="three">
						<div class="container">

							<header>
								<h2>About Us</h2>
							</header>


						</div>
					</section>

				<!-- Contact -->
					<section id="contact" class="four">
						
							

					</section>

			</div>

		<!-- Footer -->
			<div id="footer">
				<hr style="clear:both;margin-bottom:3%; width:80%;border: 1.5px solid #988;">
				<!-- Copyright -->
					<ul class="copyright" style="float:right;margin-right:100px;">
						<li>Designed by: <a href="#" target="blank">Group 12</a></li>
					</ul>

			</div>

		<!-- Scripts -->
			<script src="{% static 'plants/js/jquery.min.js' %}"></script>
			<script src="{% static 'plants/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'plants/js/jquery.scrollzer.min.js' %}"></script>
			<script src="{% static 'plants/js/skel.min.js' %}"></script>
			<script src="{% static 'plants/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'plants/js/main.js' %}"></script>

	</body>
</html>

plants/templates/userdashboard.html
{% load staticfiles%}
<!DOCTYPE HTML>

<html>
	<head>
		<title>Water Management System</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static 'plants/css/main.css' %}" />
		<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">-->
		
	</head>
	<body>

		<!-- Header -->			<div id="header">

				<div class="top">

					<!-- Logo -->
						<div id="logo">
							<span class="image avatar48" style="background-color:inherit !important;"><img src="{% static 'plants/images/man.svg' %}" alt="" /></span>
							<h1 id="title">{{ username }}</h1>
							
						</div>

					<!-- Nav -->
						<nav id="nav">
							<!--

								Prologue's nav expects links in one of two formats:

								1. Hash link (scrolls to a different section within the page)

								   <li><a href="#foobar" id="foobar-link" class="icon fa-whatever-icon-you-want skel-layers-ignoreHref"><span class="label">Foobar</span></a></li>

								2. Standard link (sends the user to another page/site)

								   <li><a href="http://foobar.tld" id="foobar-link" class="icon fa-whatever-icon-you-want"><span class="label">Foobar</span></a></li>

							-->
							<ul>
								<!-- <li><a href="#top" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-home">Map</span></a></li> -->
								<li><a href="#about" id="about-link" class="skel-layers-ignoreHref"><span class="icon fa-user">About Us</span></a></li>

								<li><a href="/addwaterdata/" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">Add Water Data</span></a></li>
								<li><a href="/search_waterdata/" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">Search Water Data</span></a></li>
								<li><a href="/all_waterdata/" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">All Water Data</span></a></li>
								

								<a href="{% url 'auth_part:logout' %}"><button style="margin-right: 20px;margin-top: 10px;">Logout</button></a>								
								<center><li>Your Water Data</li></center>
								<hr/>								
								{% for plant in plants %}
									{% if plant.alias %}
										<a style="text-align:center;" href="{{plant.get_absolute_url}}"><div style="font-size:1rem; font-weight:bold;">{{plant.alias}}</div></a><hr/>
									{% else %}
										<a style="text-align:center;" href="{{plant.get_absolute_url}}"><div style="font-size:1rem; font-weight:bold;">{{plant.alias}}</div></a><hr/>
									{% endif %}		
									</a>
								{% endfor %}
							</ul>
						</nav>

				</div>

			<!--	<div class="bottom">

					
						<ul class="icons">
							<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
							<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
							<li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
						</ul>

				</div> -->

			</div>

		<!-- Main -->
			<div id="main">

				<!-- Intro -->
					<section id="top" class="one dark cover">
						<div class="container">

						
						</div>
					</section>

			

				<!-- About Us -->
					<section id="about" class="three">
						<div class="container">

							<header>
								<h2>About Us</h2>
							</header>

						
							<p>Water quality  management is the activity of planning, developing, distributing and managing the optimum use of water resources.</p><p></b></p>

						</div>
					</section>

				<!-- Contact -->
					<section id="contact" class="four">
						
					</section>

			</div>

		<!-- Footer -->
			<div id="footer">
				<hr style="clear:both;margin-bottom:3%; width:80%;border: 1.5px solid #988;">
				<!-- Copyright -->
					<ul class="copyright" style="float:right;margin-right:100px;">
						<li>Designed by: <a href="#" target="blank">Group 12</a></li>
					</ul>

			</div>

		<!-- Scripts -->
			<script src="{% static 'plants/js/jquery.min.js' %}"></script>
			<script src="{% static 'plants/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'plants/js/jquery.scrollzer.min.js' %}"></script>
			<script src="{% static 'plants/js/skel.min.js' %}"></script>
			<script src="{% static 'plants/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'plants/js/main.js' %}"></script>

	</body>
</html>